config/routes.rb
Treefinger::Application.routes.draw do
  root to: 'pages#home'

  post '/', to: 'users#create', as: :users
  get '/ui/(:action)', controller: 'ui'

  resources :users, only: :new


  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  post '/sign_in', to: 'sessions#create', as: :sign_in


  get '/new', to: 'projects#new', as: :new_project


  resources :tasks, only: [] do
    resources :notes, only: [:index, :create]
  end

  resources :projects, only: [:create, :update] do
    resources :tasks, only: [:index, :update]
    resource  :tasks, only: :create
  end

  get '/:username', to: 'pages#dashboard', as: :dashboard
  patch '/:username/:project_name', to: 'projects#update', as: :update_project

  get '/:username/:project_name', to: 'projects#show', as: :show_project
  get '/:username/:project_name/edit', to: 'projects#edit', as: :edit_project

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :task
  belongs_to :user

  validates :body, presence: true

  delegate :username, to: :user

  default_scope ->(){order(created_at: :asc)}
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validate :project, :user, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :task
  belongs_to :user

  validates :body, presence: true

  delegate :username, to: :user
end

app/models/nil_project.rb
class NilProject
  def name
    "New Project"
  end

  def nil?
    true
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :task
  belongs_to :user

  validates :body, presence: true

  delegate :username, to: :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy

  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  validate :name, with: Validations::SLUG
  validates_uniqueness_of :name, scope: :user_id

  before_validation :underscore

  def self.find_by_name(name)
    find_by(name: name)
  end

  private

  def underscore
    self.name = name.parameterize.underscore
  end
end

app/models/task.rb
class Task < ActiveRecord::Base

  attr_accessor :user

  Actions = {
    nil         => 'start',
    'started'   => 'finish',
    'finished'  => 'restart',
    'restarted' => 'finish'
  }

  belongs_to :project
  has_many :notes, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :activities

  default_scope ->(){order(created_at: :desc)}

  def action
    Actions[status]
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  include Authem::User

  has_many :projects

  has_many :collaborations
  has_many :shared_projects, through: :collaborations, source: :project

  validate :username, with: Validations::SLUG

  def all_projects
    (projects  + shared_projects).sort_by(&:name)
  end
end

app/models/validations.rb
module Validations
  SLUG = /^[\w|-]+$/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include Authem::ControllerSupport

  before_filter :require_user

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  expose(:task)
  expose(:activities) { task.activities }
  expose(:notes) { task.notes }
  expose(:new_note) do
    notes.build(note_params) do |note|
      note.user = current_user
    end
  end

  def index
    render json: NoteRepresenter.wrap(activities)
  end

  def create
    respond_to do |format|
      if new_note.save
        format.json { render json: NoteRepresenter.new(new_note), status: :created }
      else
        format.json { render json: new_note.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :require_user, only: :home

  layout 'session', only: :home

  expose(:user) { User.new }
  expose(:projects) { current_user.all_projects }

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  expose(:projects) { current_user.projects }
  expose(:tasks) { project.tasks.to_json }

  expose(:project,
         finder: :find_by_name,
         finder_parameter: :project_name,
         attributes: :project_params,
         parent: :current_user)

  def create
    if project.save
      redirect_to dashboard_path(current_user.username)
    else
      render :new
    end
  end

  def update
    if project.save
      redirect_to dashboard_path(current_user.username)
    else
      render :edit
    end
  end

  private

  def project_name
    params[:project_name]
  end

  def project_params
    params.require(:project).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_user

  expose(:user) do
    User.where('email = :query OR username = :query', query: email_or_username).first
  end

  def create
    if user && user.authenticate(password)
      sign_in(user)
      redirect_to dashboard_path(current_user.username)
    else
      redirect_to :root
    end
  end

  def destroy
    sign_out
    redirect_to :root
  end

  private

  def email_or_username
    session_params[:email_or_username]
  end

  def password
    session_params[:password]
  end

  def session_params
    params.permit(:password, :email_or_username)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  expose(:project) { current_user.projects.find(params[:project_id]) }
  expose(:tasks) { project.tasks }
  expose(:task, attributes: :task_params)

  def index
    render json: TaskRepresenter.wrap(tasks)
  end

  def create
    task.events.build(body: event_body, user: current_user) if event_body.present?
    render json: TaskRepresenter.new(task) if task.save
  end
  alias update create

  private

  def task_params
    params.require(:task).permit(
      :name,
      :description,
      :task_string,
      :status
    )
  end

  def event_body
    params[:task][:status]
  end


end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  skip_before_filter :require_user
  layout :choose_layout

  private

  def choose_layout
    case action_name
    when 'home'
      "ui_session"
    when 'dashboard'
      "application"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_user, only: :create
  layout 'session', only: :create

  expose(:user) { User.new(user_params) }

  def create
    if user.save
      sign_in(user)
      redirect_to dashboard_path(current_user.username)
    else
      render 'pages/home'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Treefinger
    = csrf_meta_tags
    = yield :head
    = stylesheet_link_tag "application"
  %body
    %header#main
      %section.session
        You are signed in as
        %span.user #{current_user.username}
        | #{link_to 'view all projects', dashboard_path(current_user.username)}
        | #{link_to 'add project', :new_project}
        | #{link_to 'sign out', :sign_out}
      %h1= link_to "TreeFinger", root_path
      = yield :project
    %section#content
      = yield

app/views/layouts/session.html.haml
!!!
%html 
  %head 
    %title Treefinger
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #main_container
      %header
        %h1 Tree Finger
        = form_tag :sign_in, class: "sign_in" do
          %fieldset
            %dl
              %dt= label_tag :email_or_username
              %dd= text_field_tag :email_or_username
            %dl
              %dt= label_tag :password
              %dd= password_field_tag :password
          %fieldset.actions
            %input(type="submit" value= "Sign in")
      #content= yield

app/views/layouts/ui_application.html.haml
!!!
%html 
  %head 
    %title Treefinger
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/ui_session.html.haml
!!!
%html 
  %head 
    %title Treefinger
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #main_container
      %header
        %h1 Tree Finger
        %form.sign_in
          %fieldset
            %dl
              %dt
                %label Email or username
              %dd
                %input(type="email")
            %dl
              %dt
                %label Password
              %dd
                %input(type="password")
          %fieldset.actions
            %input(type="submit" value= "Sign in")
      #content= yield

app/views/pages/dashboard.html.haml
%ul.projects
  - projects.each do |project|
    %li= link_to project.name, show_project_path(current_user.username, project.name)

app/views/pages/home.html.haml
%article#home
  %header
    %h1 A project & task manager
    %h2 for people who hate using project and task managers
  %p Tree Finger is the world’s simplest project manager: just add and edit items using indentation (that thing you learned in elementary school).  Managing your workflow has never been easier!
  %footer Use treefinger and ride ponies with the time you save

%aside#sign_up
  %h1
    Sign up

  = form_for user do |f|
    %fieldset
      %dl
        %dt= f.label :username
        %dd= f.text_field :username
        %dt= f.label :email
        %dd= f.email_field :email
        %dt= f.label :password
        %dd= f.password_field :password
        %dt= f.label :password_confirmation
        %dd= f.password_field :password_confirmation
    %fieldset
      = f.submit "Register for free"

app/views/projects/_fields.html.haml
%fieldset
  %dl
    %dt= f.label :name
    %dd= f.text_field :name
%fieldset
  = f.submit

app/views/projects/edit.html.haml
#project_settings
  %section
    %h2 Edit => #{project.name}
    = form_for project, url: update_project_path(current_user.username, project.name) do |f|
      = render 'fields', f: f

app/views/projects/new.html.haml
#project_settings
  %section
    %h2 Create new Proect
    = form_for project do |f|
      = render 'fields', f: f

app/views/projects/show.html.haml
= content_for :head do
  = javascript_include_tag "application"
  :javascript
    window.project_id = "#{project.id}";

= content_for :project do
  %h2= project.name
  %nav.project_nav
    = link_to "Edit Project", edit_project_path(current_user.username, project.name)

#project
  %section#editor_border
  %section#editor(contenteditable="true" spellcheck="false")
  %section#tasks
    %ul
  %section#notes
    .note_container
      %ul.notes
    %form.new_note
      %fieldset
        %textarea#note_text(placeholder="Note...")
      %fieldset.actions
        %input(type="submit" value="Add note")

app/views/ui/dashboard.html.haml
%section#editor

%section#tasks
  %ul
    %li.active.noted
      .left_arrow
      .right_arrow
      User signs up
      .actions
        = link_to "accept", "#", class: 'complete'
        |
        = link_to "notes", "#", class: 'view'
    %li.active
      User signs in
      .left_arrow
      .actions
        = link_to "accept", "#", class: 'complete'
        |
        = link_to "notes", "#", class: 'view'
    %li
      .left_arrow
      User signs out
      .actions
        = link_to "deliver", "#", class: 'complete'
        |
        = link_to "notes", "#", class: 'view'
    %li
      User edits account
      .actions
        = link_to "deliver", "#", class: 'complete'
        |
        = link_to "notes", "#", class: 'view'
%section#notes
  .note_container
    %ul.notes
      - 2.times do
        %li
          %p.username mrmicahcooper
          %p.note When I click the forgot password linke, I get a 404 error. Thats' unexpected and I do nt' liek it. Can you do something else right there that isn't so anoying. maybt a helpful page or something?
  %form.new_note
    %fieldset
      %textarea{ placeholder: "Note..." }
    %fieldset.actions
      = link_to "attach a file", "#"
      %input(type="submit" value="Add note")

app/views/ui/home.html.haml
%article#home
  %header
    %h1 A project & task manager
    %h2 for people who hate using project and task managers
  %p Tree Finger is the world’s simplest project manager: just add and edit items using indentation (that thing you learned in elementary school).  Managing your workflow has never been easier!
  %footer Use treefinger and ride ponies with the time you save

%aside#sign_up
  %h1
    Sign up
    %small or
    %a(href="#") sign in with github

  %form
    %fieldset
      %dl
        %dt
          %label Username
        %dd
          %input(type="text")
        %dt
          %label Email address
        %dd
          %input(type="email")
        %dt
          %label Password
        %dd
          %input(type="password")
        %dt
          %label Confirm Password
        %dd
          %input(type="password")
    %fieldset
      %input(type="submit" value="Sign Up")

app/views/ui/index.html.haml
%ul
  - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
    - wireframe = File.basename(file,'.html.haml')
    -  unless wireframe == 'index' || wireframe.match(/^_/)
      %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'